/**
 * colorPalette.js
 * 모든 차트 오퍼레이션에서 사용하는 통일된 색상 팔레트
 */
export const COLOR_PALETTE = {
    RED: "#e03131",
    YELLOW: "#fab005",
    BLUE: "#339af0",
    PURPLE: "#a65dfb",
    TEAL: "#20c997",
    ORANGE: "#fd7e14",
    GREEN: "#2e7d32",
    DARK_RED: "#d32f2f",
    LIGHT_BLUE: "#0d6efd",
    HIGHLIGHT: "#ff6961",
};

export const OP_COLORS = {
    RETRIEVE_VALUE: COLOR_PALETTE.HIGHLIGHT,
    FILTER_MATCH: COLOR_PALETTE.ORANGE,
    FILTER_THRESHOLD: COLOR_PALETTE.BLUE,
    EXTREMUM: COLOR_PALETTE.PURPLE,
    RANGE: COLOR_PALETTE.LIGHT_BLUE,
    COMPARE_A: COLOR_PALETTE.YELLOW,
    COMPARE_B: COLOR_PALETTE.BLUE,
    COMPARE_WINNER: COLOR_PALETTE.GREEN,
    SUM: COLOR_PALETTE.RED,
    AVERAGE: COLOR_PALETTE.RED,
    DIFF_A: COLOR_PALETTE.YELLOW,
    DIFF_B: COLOR_PALETTE.BLUE,
    DIFF_LINE: COLOR_PALETTE.DARK_RED,
    NTH: COLOR_PALETTE.TEAL,
    COUNT: COLOR_PALETTE.TEAL,
    TRUE: COLOR_PALETTE.GREEN,
    FALSE: COLOR_PALETTE.DARK_RED,
};