export const OperationType = Object.freeze({
    RETRIEVE_VALUE: "retrieveValue",
    FILTER: "filter",
    FIND_EXTREMUM: "findExtremum",
    DETERMINE_RANGE: "determineRange",
    COMPARE: "compare",
    COMPARE_BOOL: "compareBool",
    SORT: "sort",
    STACK: "stack",
    SUM: "sum",
    AVERAGE: "average",
    DIFF: "diff",
    LAG_DIFF: "lagDiff",
    NTH: "nth",
    COUNT: "count",
});
