import type { DatumValue, OperationSpec } from '../../../types'
import { OperationOp } from '../../../types'
import {
  addData,
  retrieveValue,
  filterData,
  findExtremum,
  sortData,
  sumData,
  averageData,
  diffData,
  lagDiffData,
  pairDiffData,
  nthData,
  scaleData,
  compareBoolOp,
  countData,
  diffByValueOp,
  rangeData,
  rollingWindowData,
  monotonicRunData,
} from '../../../operation/run/dataOps'

export const STANDARD_DATA_OP_HANDLERS: Record<string, (data: DatumValue[], op: OperationSpec) => DatumValue[]> = {
  [OperationOp.RetrieveValue]: retrieveValue,
  [OperationOp.Filter]: filterData,
  [OperationOp.FindExtremum]: findExtremum,
  [OperationOp.CompareBool]: compareBoolOp,
  [OperationOp.DiffByValue]: diffByValueOp,
  [OperationOp.Sort]: sortData,
  [OperationOp.Sum]: sumData,
  [OperationOp.Average]: averageData,
  [OperationOp.Diff]: diffData,
  [OperationOp.LagDiff]: lagDiffData,
  [OperationOp.PairDiff]: pairDiffData,
  [OperationOp.Nth]: nthData,
  [OperationOp.Count]: countData,
  [OperationOp.Add]: addData,
  [OperationOp.Scale]: scaleData,
  [OperationOp.Range]: rangeData,
  [OperationOp.RollingWindow]: rollingWindowData,
  [OperationOp.MonotonicRun]: monotonicRunData,
}
