export const DataAttributes = {
  Id: 'data-id',
  Target: 'data-target',
  Value: 'data-value',
  Series: 'data-series',
  ChartId: 'data-chart-id',
  ChartPanel: 'data-chart-panel',
  PanelPlotX: 'data-panel-plot-x',
  PanelPlotY: 'data-panel-plot-y',
  PanelPlotWidth: 'data-panel-plot-w',
  PanelPlotHeight: 'data-panel-plot-h',
  AnnotationKey: 'data-annotation-key',
  AnnotationNodeId: 'data-annotation-node-id',
  AnnotationLifecycle: 'data-annotation-lifecycle',
  RenderEpoch: 'data-render-epoch',
  AxisRotation: 'data-axis-rotation',
  TickDensityStep: 'data-tick-density-step',
  MarginLeft: 'data-m-left',
  MarginTop: 'data-m-top',
  ExplanationTop: 'data-explanation-top',
  ExplanationHeight: 'data-explanation-height',
  ExplanationBottom: 'data-explanation-bottom',
  AnnotationTopClearance: 'data-annotation-top-clearance',
  PlotWidth: 'data-plot-w',
  PlotHeight: 'data-plot-h',
  XField: 'data-x-field',
  YField: 'data-y-field',
  XSortOrder: 'data-x-sort-order',
  ColorField: 'data-color-field',
  FacetField: 'data-facet-field',
  XLabel: 'data-x-label',
  YLabel: 'data-y-label',
  GroupLabel: 'data-group-label',
  XValue: 'data-x-value',
  YValue: 'data-y-value',
  GroupValue: 'data-group-value',
} as const

export type DataAttribute = (typeof DataAttributes)[keyof typeof DataAttributes]

export const SvgElements = {
  Svg: 'svg',
  Group: 'g',
  Rect: 'rect',
  Path: 'path',
  Circle: 'circle',
  Text: 'text',
  Line: 'line',
  TSpan: 'tspan',
} as const

export type SvgElementTag = (typeof SvgElements)[keyof typeof SvgElements]

export const SvgAttributes = {
  Class: 'class',
  D: 'd',
  X: 'x',
  Y: 'y',
  X1: 'x1',
  X2: 'x2',
  Y1: 'y1',
  Y2: 'y2',
  Width: 'width',
  Height: 'height',
  Fill: 'fill',
  Stroke: 'stroke',
  StrokeWidth: 'stroke-width',
  StrokeDasharray: 'stroke-dasharray',
  Opacity: 'opacity',
  TextAnchor: 'text-anchor',
  DominantBaseline: 'dominant-baseline',
  FontSize: 'font-size',
  FontWeight: 'font-weight',
  FontFamily: 'font-family',
  Transform: 'transform',
  RX: 'rx',
  CX: 'cx',
  CY: 'cy',
  R: 'r',
  PaintOrder: 'paint-order',
  ViewBox: 'viewBox',
} as const

export type SvgAttribute = (typeof SvgAttributes)[keyof typeof SvgAttributes]
