export const OperationOp = {
    Draw: 'draw',
    RetrieveValue: 'retrieveValue',
    Filter: 'filter',
    FindExtremum: 'findExtremum',
    DetermineRange: 'determineRange',
    Compare: 'compare',
    CompareBool: 'compareBool',
    Sort: 'sort',
    Sum: 'sum',
    Average: 'average',
    Diff: 'diff',
    LagDiff: 'lagDiff',
    Nth: 'nth',
    Count: 'count',
    Sleep: 'sleep',
};
